version: "3.8"
services:
  kajiapp:
    container_name: kajiAppblazor2
    image: kajiappblazor2
    ports:
      - "22787:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:32787
    restart: unless-stopped